### ISSUE TITLE
rethink abstract data class

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#11]
A rethink data class that implements a validate function against a json-schema identified by a Catalogue URL that can be retrieved from the Catalogue Runtime. This function is called in debug mode. All other reTHINK data classes that should comply with a standard json-schema will extend from this abstract data class.

**Comment by pchainho** [comment]
The Json-schema for the validation of data objects used in the data synchronisation between hyperties are ready and available [here](https://github.com/reTHINK-project/dev-service-framework/tree/develop/schemas/json-schema/data-objects)

@acheambe  pls provide us some feedback

thx

**Comment by pchainho** [comment]
What is the status of this one?

**Comment by Endebert** [comment]
[I went ahead and extended the (optional) vaidation of RethinkObjects](https://github.com/reTHINK-project/dev-service-framework/blob/develop/src/reTHINKObject/RethinkObject.js)

Now the question is when to use this feature. It works well in the karma tests, for example I added validation as part of the tests for the [MessageFactory](https://github.com/reTHINK-project/dev-service-framework/blob/develop/test/MessageFactory.spec.js)

[The object validation I added to the SyncherManager in dev-runtime-core](https://github.com/reTHINK-project/dev-runtime-core/blob/develop/src/syncher/SyncherManager.js#L106) works similarly, but doesn't need the RethinkObject class. 

In both cases, we have to enforce that the schemas that are being validated against do not contain any references to other schemas, since they might not be resolveable. For the validation with RethinkObjects in karma tests, I suggest the provision of another set of json schemas, that are also contained in dev-service-framework, but have their references already resolved. I believe that could be done easily with a gulp task.

**Comment by Endebert** [comment]
Since this issue is about the RethinkObject class, which is implemented and contains validation functionalities, this issue can be closed.

 The gulp task I mentioned in my previous comment has been added by me [some time ago](https://github.com/reTHINK-project/dev-service-framework/commit/922bdc7e166ee50bb168d3cc34bc2567fc20bf4b)
