### ISSUE TITLE
update json-schema generation with new package structure.

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#22]
Update json-schema generation tool according to new package structure as discussed in #16 

json-schema generation tool should be moved to this repo: src/tools

**Comment by shumy** [comment]
Another problem that as came up is related to mismatch between UML definitions and JSON Schema. This is not a technical problem and there's nothing wrong with the actual generated schemas, it's just, they are not as useful as it seems.
The way JSON Schema is validated, is starting on a root object and verifies every field and reference attached to it. However class diagrams don't strictly follow a tree structure. Even if we define a root object, if there are detached definitions (with inverted references), these are not validated.
JSON schema is directly related to document databases. But class diagramas define better, relational databases.
I don't see a way to solve this, unless carefully designing the class diagrams. By following a tree structure and by separating in different packages.
Any ideas are wellcome.

**Comment by shumy** [comment]
Found other minor issues:
1. How to define some special types. Currently URL's are defined as classes, these are converted to JSON object definitions. However URL's are formatted strings instead.
2. When defining a reference in PlantUML like ```ClassX --> ClassY``` there is no place to define the reference variable name. The placeolder after the definition could be used like ```ClassX --> ClassY:name``` but this is currently defined as free text (not suitable to a variable name, because it can have spaces).
3. There are some circular references in the model and can be a problem when validating data, creating infinite loops.
4. There are no arrays or references to native types.

Some proposed solutions:
1. Use the PlantUML feature "specific spot" to define custom type elements.
Just add <<(T,orchid)>> to the class definition to be a Type definition.
2. Use the relation description for variable name, and drop the general purpose.
3. Do not generate inverted references. For example ```ClassX --> ClassY``` will be the same as ```ClassX -- ClassY``` assuming the left to right direction.
But I would rather prefer that UML be corrected instead.
4. Should be defined as "field: type[]"

**Comment by pchainho** [comment]
> 1. Use the PlantUML feature "specific spot" to define custom type elements.
Just add <<(T,orchid)>> to the class definition to be a Type definition.

ok

> 2. Use the relation description for variable name, and drop the general purpose.

We agreed to ignore associations like ClassX --> ClassY and to just take into account attributs defined in each class.

> 3. Do not generate inverted references. For example ClassX --> ClassY will be the same as ClassX -- ClassY assuming the left to right direction.

This one should not be an issue anymore since we agreed to ignore plantuml associations

> 4. Should be defined as "field: type[]"

ok

**Comment by shumy** [comment]
Parser was not prepared to accept relations beetween packages. It's was updated, but no JSON is generated for this.

**Comment by shumy** [comment]
Parser was updated, and schemas generated.
1. Code and tool available at "tools/plantuml-json-parser/"
2. Model sources available at "schemas/"
3. JSON Schemas available at "docs/datamodel/json-schema/"

**Comment by pchainho** [comment]
Not done according to previously agreed structure

**Comment by pchainho** [comment]
partially done according to agreed structure. It is ready to be used for the validation of data synch objects.
