### ISSUE TITLE
Syncher: addObserver() / inviteObserver()

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#37]
Adicionar função para convidar um Observer depois do objecto criado:

inviteObserver( URL.HypertyUrl observer)

**Comment by shumy** [comment]
There is no specification of the flow messages. Especially the initial messages between the Syncher and SyncherManager. I don't think the same create message can be reused, because it's an invite, not a creation process?
I suppose the message between SyncherManager and the ObserverHyperty is the same as the one used for create process.

**Comment by pchainho** [comment]
The syncher can use the same Create() message having the in the body the ObjectURL that the sync manager will check already exists.

**Comment by shumy** [comment]
New method "inviteObservers(URL.HypertyUrl[] observers)" added to DataObjectReporter. Passing an array is better, it's in compliance with the Syncher.create.
