### ISSUE TITLE
Find a specific hyperty per schema and user

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-service-framework#44]
When i try to get an specific hyperty like chat, i invoke [advancedSearchPerHyperty(user, schema, resources, domain)](https://github.com/reTHINK-project/dev-service-framework/blob/develop/src/discovery/Discovery.js#L156) we should have and array of hyperties, but only have this message result;

![screenshot from 2016-05-27 11-29-35](https://cloud.githubusercontent.com/assets/10596749/15605520/57f22efa-23fe-11e6-9ca4-5b399d256e26.png)

**Comment by vitormsilva** [comment]
This issue was partial solved because I'm using an old version of msg-node-vertx and domain-registry, I update and got the correct answer.

But I have one more doubt, the user parameter, need to be like `user://gmail.com/openidtest10` or should be and email like `openidtest10@gmail.com`?

**Comment by gamdias** [comment]
> But I have one more doubt, the user parameter, need to be like user://gmail.com/openidtest10 or should be and email like openidtest10@gmail.com?

Added the support of both userURL and user email options. Any problem, please report.

**Comment by vitormsilva** [comment]
The method has changed.. now is [discoveryHyperty](https://github.com/reTHINK-project/dev-service-framework/blob/develop/src/discovery/Discovery.js#L160), and it works.

My doubt now is related with [registerHyperty resources](https://github.com/reTHINK-project/dev-runtime-core/blob/dev-0.5/src/registry/Registry.js#L346), now is hard coded, you can fix this? Because when I look for scheme in this discoveryHyperty, as all are registered with the same resource it returns all hyperties and I can't distinguish each one;

if you need help, i can try to help you..

**Comment by gamdias** [comment]
About the resourcesFake/dataSchemesFake, they were created until I get the right information about the resources and schemas.

I think that some changes are needed so that I can access that information, and either are passed in the hyperty descriptor or the method registerHyperty is changed to support this information in the params received. Example: `registerHyperty(sandbox, descriptor, resources, schema)`

**Comment by pchainho** [comment]
In order to fix this issue the following tasks are required:

1- pass the runtime catalogue in the runtime registry constructor -> @vitormsilva 

2- registry.registerHyperty(sandbox, descriptor) : query the runtime catalogue about hyperty descriptors and supported data object schemas, collect data from them e embed them in the registration message body -> @gamdias 

3- complete demos descriptors to be used in the tests -> @vitormsilva 

4- correct hypertyDiscovery, removed hardcoded results, and appropriately query the domain registry about active Hyperties -> @gamdias

**Comment by vitormsilva** [comment]
From my side:

1- pass the runtime catalogue in the runtime registry constructor: **done**
3- complete demos descriptors to be used in the tests: **done**

If something is not right, let me know

**Comment by gamdias** [comment]
I've updated the runtime registry and now receives the schemas and resources from the catalogue.

Step 1 is **done**, step 4 is also **done**. 
The last thing missing is registry.unregisterAll() from this issue https://github.com/reTHINK-project/dev-runtime-core/issues/89

Please test to see if it's alright.

**Comment by vitormsilva** [comment]
Seems resolved.
Closing;
