### ISSUE TITLE
Message Factory with wrong type on field "id"

### ISSUE THREAD

**Issue by gamdias** [reTHINK-project/dev-service-framework#57]
I had to remove temporarily the Message Factory from the Runtime Registry because it causes problems on messages sent to the domain registry.

The error in the domain registry:
`SEVERE: Unhandled exception
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at io.vertx.core.json.JsonObject.getInteger(JsonObject.java:281)
	at eu.rethink.mn.pipeline.message.PipeMessage.getId(PipeMessage.java:63)...
`

It might be a problem on the generation of the ID field in the message factory:
`let id = "" + this.myGenerator.next().value;` 
This produces a string instead of a number.

**Comment by Endebert** [comment]
>This produces a string instead of a number.

As it should, according to the datamodel: https://github.com/reTHINK-project/dev-service-framework/tree/master/docs/datamodel/core/message

**Comment by luistduarte** [comment]
Some messages are with string(from MessageFactory) others are with number.

What i did for solve this was, instead of
`msg.getInteger("id",0);`
i am using now 
`msg.getValue("id","0").toString();`

With this, it can accept String or Integer.

**Comment by pchainho** [comment]
as far as I remember it was decided to have "integer" for this field. I'll updated the data model

**Comment by Endebert** [comment]
When was this decided? Was this decision noted somewhere else and I missed it? Because I specifically changed the type of this field, so that it would comply with the data model and the corresponding json schema.

@pchainho , when you update the data model, please also update the corresponding json schema and the MessageFactory and Message classes.

**Comment by pchainho** [comment]
A long time ago and I forgot to update the model, worry

I've just updated the json schema but MessageFactory was developed by Fokus

**Comment by pchainho** [comment]
Perhaps I was wrong and no decision was taken to change the type. @sdruesedow, @NicoApizee can you confirm this, pls?

Anyway, since the "message.id" has to be incremented for every new Request message, I would be in favor to have it as an "integer": opinions?

**Comment by sdruesedow** [comment]
The situation:
The original specification defined the message-id as <String>. The type was changed to integer about a month ago (see: https://github.com/reTHINK-project/dev-service-framework/commit/c0d70c527696ad7f48a88edc611d2e18f9101e23 ). ALL the example messages still have the id as String. The MessageFactory has recently updated it to integer (see: https://github.com/reTHINK-project/dev-service-framework/commit/da3d00a5ec0376d1f3cb70d30cfbcade3ca73573 ).

Historically only the Vertx node assumed integers and had problems with the specified String ids, since it is implemented in Java. This behavior was already documented in D6.3, where the MNs have beed tested. The tests had to be "relaxed" (to use integer IDs) to make them also work on Vertx.

My proposal is to go on with integers from now on and to update all the message examples in the new spec repository also to integer. (... since examples are what developers are looking for).

**Comment by pchainho** [comment]
This change has already been done at [p2p-specs branch](https://github.com/reTHINK-project/specs/tree/p2p-specs/messages)

**Comment by pchainho** [comment]
done
