### ISSUE TITLE
catalogue source packages aren't saved in the local storage

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-service-framework#60]
Hi,

The source package of the runtime, hyperties, etc, are always downloaded from the Catalogue and is not from the local storage.

When we analyse the URL's saved on local storage, we see the the descriptor has the sourcePackageURL, so, we will call the method getSourcePackageFromURL(sourcePackageURL) and this method, doesn't save on the local storage that URL with the respective source code.

**Comment by Endebert** [comment]
This is intended behaviour, because: How is the RuntimeCatalogue supposed to know if the sourcePackage stored in localstorage represents the current version? The version is present in the descriptor part, but not in the sourcePackage, so `getSourcePackageFromURL(sourcePackageURL)` can't make use of the persistencemanager and never will.

[However, the revised RuntimeCatalogue in the `revised-catalogue` branch by default returns the full object (descriptor + sourcePackage) and also saves it with the persistencemanager into localstorage.](https://github.com/reTHINK-project/dev-service-framework/blob/revised-catalogue/src/runtime-catalogue/RuntimeCatalogue.js#L80)

**Comment by Endebert** [comment]
Seems this can be closed.

**Comment by pchainho** [comment]
pls keep it open since the issue is still there and if I got you right it has a dependency with https://github.com/reTHINK-project/dev-runtime-core/issues/101

**Comment by emmelmann-fokus** [comment]
No further actions scheduled for @Endebert .  Changing assignee to allow Paulo to have an eye on the issue and to condense the number of open issues for Fokus that need to be taken care of.

**Comment by pchainho** [comment]
this one is fixed
