### ISSUE TITLE
Runtime Catalogue: cguid usage at persistence manager

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#64]
Following reTHINK-project/dev-catalogue#50 , at this point cguid can't be used as the key when storing in the persistence manager. Use catalogue URL instead.

We should give priority to this one

**Comment by Endebert** [comment]
While using the catalogue URL instead of the cguid as the key when storing descriptors with the persistence manager would be an easy workaround, I still disagree that the cguid cannot be used as a key.

Let's say we have a descriptor "A", and this descriptor has the cguid "1". Now, if you create a new descriptor "B" based on descriptor "A", and change __anything__ in the descriptor object, __it has to get a new cguid__. The reason is that the cguid represents the complete descriptor object, including all parts. 

The simplest example is when using the "default" hyperties/protostubs, etc.:

Assuming there is a hyperty "myHyperty" that is set up as the default hyperty, then we have two resource paths:

1. `/.well-known/hyperty/myHyperty`
2. `/.well-known/hyperty/default`

While they have different different resource path, they both point to the same object. But how can I know that? Because of the __cguid__. With the workaround, we would now store the same object twice.

Now, if you have `myHyperty` in two different catalogues, as long as they are identical, they should have the same cguid.

__But__, if you change _anything_ of `myHyperty` in the second catalogue (e.g. the configuration), then they are not identical anymore, and they __have to have differing cguids__.

I know that, currently, we have no means of verifying the cguids on a global scale, but until then, simply use randomly generated cguids. The chances of using the same guid that way is incredibly small.

And changing the cguid value is an even easier fix than changing the code of the RuntimeCatalogue.

**Comment by pchainho** [comment]
the last version of the toolkit already generates a cguid when the hyperty is changed or when `gulp encode` is executed. That's not the problem. 

As mentioned somewhere else, the issue is when you have descriptors that are domain specific and they are not generated by the toolkit. For example, the Vertx protostub is used as default for our testbed and quobis testbed, and, since we have no provisioning tool, the configuration is set by hand, and usually people don't change the cguid. 

Since at this point, this problem only occurs for default protostubs, a workaround is: use by default cguid but for default protostubs, where the catalogue URL would be used.

**Comment by Endebert** [comment]
> the configuration is set by hand, and usually people don't change the cguid

I would rather have a remark in the documentation about this, than changing the code of the RuntimeCatalogue. I.e. "Beware that if you modify the descriptor and/or the sourcePackage, you also have to change the cguid"

**Comment by pchainho** [comment]
> I would rather have a remark in the documentation about this

where?

Nevertheless, we should not leave the enforcement of these rules to humans (that can maliciously use this weak point to cause serious damages) when they can be securely enforced by machines.

Actually, we have a simple rule to be enforced: default protostubs from different domains can't have the same cguid.

**Comment by emmelmann-fokus** [comment]
> Actually, we have a simple rule to be enforced: default protostubs from different domains can't have the same cguid.

And this is simple: if you provide a default protostub from a different domain just just fill in the CGUID field when you provide the protocol sub;  there are several well-known ways for the provider of that object to generate a ID which is globally unique.

To make the issue very transparent:  The standard says "do not cross the intersection if the traffic light for you is red".  People have to follow this and if they don't, we see accident.  The discussion we are having is that we need to prevent people from being able to cross the intersection if their traffic light is red.

All of our existing design works and we were able to spend our time on progressing phase-2 issues as we discuss how to deal with developers who are not able to google on how to generate a globally unique id that is not clashing.

The existing specification works and we would not see any issues if people followed the spec.

To progress here and help people who provide xxx-objects:   

http://bfy.tw/6jOd helps and points you directly, e.g., to https://www.guidgenerator.com which is just one means on how to do it.

Whenever you have to fill in a value for a field that asks per specification for a globally unique id, you go there and get a GUID.  

Note that this discussion only started because two providers of an object used "4000" for the GUID value.

**Comment by pchainho** [comment]
> To make the issue very transparent: The standard says "do not cross the intersection if the traffic light for you is red". People have to follow this and if they don't, we see accident. The discussion we are having is that we need to prevent people from being able to cross the intersection if their traffic light is red.

The problem is that your "traffic light" lets providers to maliciously change the lights and cause accidents. And you can prevent that in the runtime catalogue with a very simple standard rule: block the load of a default protostub which cguid is equal to a cguid from a default protostub that was previously loaded from another domain.

As already discussed, the generation of the cguid is not a problem. The toolkit already does that.

**Comment by Endebert** [comment]
To close this issue, I implemented the following solution: The Catalogue Database will ignore cguids defined in the catalogue object and instead generate a cguid automatically based on the hash of the object instead. The probability that we have 2 different catalogue objects with the same cguid/hash is about 1/2147483647. If this is not good enough we will can maybe consider further adding a salt to this.

See: https://github.com/reTHINK-project/dev-catalogue/commit/20b0df2fb13c7c8deb5c6feae5662f284a0c9187
