### ISSUE TITLE
Fix typo on Syncher create

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-service-framework#70]
@dvilchez,

Why do you change the `schema` to `scheme` on Syncher with this commit https://github.com/reTHINK-project/dev-service-framework/commit/46a591cb65604ebdec8f9767928ea807ba818192

The correct one is `schema` - https://github.com/reTHINK-project/specs/blob/master/messages/data-sync-messages.md#hyperty-data-object-creation

**Comment by sdruesedow** [comment]
This should perhaps be discussed in a more general scope, because in the address allocation message spec it is always "scheme", not "schema". (see https://github.com/reTHINK-project/specs/blob/master/messages/address-allocation-messages.md)

**Comment by dvilchez** [comment]
@vitormsilva I don't remember it was five month ago, but I'm pretty sure I didn't do it on my own.

**Comment by pchainho** [comment]
@sdruesedow 
> This should perhaps be discussed in a more general scope, because in the address allocation message spec it is always "scheme", not "schema". (see https://github.com/reTHINK-project/specs/blob/master/messages/address-allocation-messages.md)

This is a different situation. In that case it is really the URL scheme as defined by [WHATWG](https://url.spec.whatwg.org/#urls). It is provided in order to generate the URL address with the right scheme.

@dvilchez it is very important that only the repo "owners" merge or push to masters / develop branches. Others should do pull requests to these branches.

**Comment by dvilchez** [comment]
I am not sure, but I guess you asked me for doing some changes when @vitormsilva was on holiday... believe me, I don't do any change in this repo without your permission.
