### ISSUE TITLE
Runtime Catalogue Error obtaining the sourcePackage

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-service-framework#80]
When i use the runtimeCatalogue from develop branch, i have the following error, obtaining the sourcePackage.. 

![screenshot from 2017-01-16 15-30-13](https://cloud.githubusercontent.com/assets/10596749/21988914/d7bee744-dc00-11e6-8521-791a6715c244.png)

I'm using the [catalogue-database-reTHINKdefault](https://github.com/reTHINK-project/dev-catalogue/tree/master/docker/catalogue-database-reTHINKdefault).

@Endebert, could you help me?

**Comment by pchainho** [comment]
It seems there was a [merge](https://github.com/reTHINK-project/dev-service-framework/commit/fe4a3e4033858f109cb2b260f131c59a6079b1f9) and no pull request. Pls revert and check again

**Comment by Endebert** [comment]
Has this issue been resolved? Have you tried clearing localstorage? Because in the screenshot I can see that a saved version of the descriptor is taken from the storagemanager, which might be the cause of the problem.

Or maybe it is related to the broken docker image, as we discussed here: https://github.com/reTHINK-project/dev-catalogue/issues/55

**Comment by vitormsilva** [comment]
Hi @Endebert,

No, the issue was not resolved.
When I did this screenshot, started with a clean localstorage.. but tried some times.

The problem with docker image, also no, I did this after you fix the docker images.

I think it was related to the implementation of constraints you did.. I don't know, it's only a guess.. but this happening after that changes been merged to develop branch.

At this moment, the version on the develop branch has the version before you did the merge.

**Comment by Endebert** [comment]
@vitormsilva you are definitely right, there should be one of those 2 log messages before `attachRawSourcePackage` is called. I have no idea why it would skip some part of the code. 

From what I can see, there is no problem with the Catalogue Broker or Database.

My guess is that there is a bug in storageManager that causes this problem. If we look at the `getVersion` function:
```
getVersion(key) {
  console.info('[StorageManager] - getVersion for key ', key);
  return this.db[this.storageName].where('key')
    .equals(this._checkKey(key))
    .first()
    .then((object) => {
      if (object) return object.version;
    })
    .catch(error => {
      console.info('error getting the version for ', key, ' with error: ', error);
      return undefined;
    });
}
```

This part looks interesting:
```
.then((object) => {
  if (object) return object.version;
})
```
What happens if `object` is `undefined`, i.e. `if (object) -> false`? Can this even happen or is this handled in `.catch()`?

I'm assuming `.catch()` was not called, because the corresponding log message is not printed. But you said you started with a clean localstorage, so there shouldn't be anything for the storageManager to find.

_Maybe_ because there is no return in the `.then()` function, things get messed up.

Could you please try to check what happens in the `.then()` function, maybe by printing the `object`. If it is indeed `undefined`, could you please check what happens if you extend the if-clause with `else return undefined` or something like that?

Currently, that's the only solution I can think of. Even if this is not the cause of the problem, it must be related to Promise handling somehow.

To reiterate: If we look at the relevant part of the RuntimeCatalogue code...
```
let descriptorPromise = Promise.all([this.httpRequest.get(descriptorURL + "/version"), this.httpRequest.get(descriptorURL + "/cguid")]).then(([version, cguid]) => {
    console.log("got version (" + version + ") and cguid (" + cguid + ") for descriptor " + descriptorURL);

    // check if same version is contained in localStorage
    return this.storageManager.getVersion(cguid).then((dbVersion) => {
        if (dbVersion >= version) {
            console.log("storageManager contains saved version that is the same or newer than requested");
            isSavedDescriptor = true;
            return this.storageManager.get(cguid);
        } else {
            console.log("storageManager does not contain saved version");
            // no saved copy, proceed with retrieving descriptor
            return this.httpRequest.get(descriptorURL).then((descriptor) => {
                descriptor = JSON.parse(descriptor);
                //console.log("got descriptor:", JSON.stringify(descriptor, null, 2));
                if (descriptor["ERROR"]) {
                    // TODO handle error properly
                    throw new Error(descriptor);
                } else {
                    return descriptor;
                }
            });
        }
    })

}).catch((error) => {
    let errorString = "Unable to get descriptor for " + descriptorURL + ": " + error;
    console.error(errorString);
    throw new Error(errorString);
});
```

We know that:
1. `Promise.all()` was resolved
2. `Promise.all().then()` was called with argument `[version, cguid]`
3. inside of that function, `this.storageManager.getVersion(cguid)` was called, but
4. `this.storageManager.getVersion(cguid).then()` was never called, instead
5. `this.attachRawSourcePackage()` was called with argument `[version, cguid]` (which is strange)
6. things break

The weirdest thing about this is that `attachRawSourcePackage` should never be called with `[version, cguid]` no matter what. I would assume that, if anything, `attachRawSourcePackage` would be called with `undefined`, but maybe this is some special quirk about Promises in javascript.

**Comment by pchainho** [comment]
I understand it was fixed. reopen if needed
